version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: codeigniter_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: codeigniter_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: codeigniter_db
    restart: always
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: ciuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
